package io.github.inductiveautomation.kindling.log

import io.github.inductiveautomation.kindling.core.DEFAULT_TIMESTAMP_PATTERN
import io.github.inductiveautomation.kindling.core.Kindling.Preferences.General.DefaultEncoding
import io.github.inductiveautomation.kindling.core.Kindling.Preferences.General.TimestampPattern
import java.nio.file.Path
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlin.io.path.useLines

private val DEFAULT_LOG_TIME_FORMAT: DateTimeFormatter = DateTimeFormatter.ofPattern(DEFAULT_TIMESTAMP_PATTERN)
    .withZone(ZoneId.systemDefault())

/**
 * The user's configured [TimestampPattern], or null if it is unusable or is just the stock format
 * (in which case [DEFAULT_LOG_TIME_FORMAT] already covers it).
 *
 * Resolve this once per file, so that every line in a file is parsed consistently.
 */
internal val configuredTimestampFormat: DateTimeFormatter?
    get() = TimestampPattern.currentValue
        .takeIf { it != DEFAULT_TIMESTAMP_PATTERN }
        ?.let { pattern ->
            runCatching {
                DateTimeFormatter.ofPattern(pattern).withZone(ZoneId.systemDefault())
            }.getOrNull()
        }

/**
 * A purely numeric `yyyy MM dd HH mm ss SSS` timestamp, with any non-digit separators. Lets us read a timestamp
 * written with a pattern that no longer matches the [TimestampPattern] preference, which is common for logs
 * generated by an older (or someone else's) Kindling configuration.
 */
private val NUMERIC_TIMESTAMP =
    """(\d{4})\D(\d{1,2})\D(\d{1,2})\D+(\d{1,2})\D(\d{1,2})\D(\d{1,2})(?:\D(\d{1,3}))?""".toRegex()

/**
 * Parse [value] with the [configured] pattern, falling back to the stock wrapper log format so that a
 * timestamp pattern chosen for the Logback tool can't render wrapper logs unreadable.
 *
 * If [numericFallback] is set, a final attempt is made to read the timestamp as a plain
 * `yyyy MM dd HH mm ss SSS` sequence, ignoring whatever separators were used.
 *
 * Returns null if no format applies.
 */
internal fun parseLogTimestamp(
    value: String,
    configured: DateTimeFormatter?,
    numericFallback: Boolean = false,
): Instant? {
    if (configured != null) {
        runCatching { configured.parse(value, Instant::from) }.getOrNull()?.let { return it }
    }
    runCatching { DEFAULT_LOG_TIME_FORMAT.parse(value, Instant::from) }.getOrNull()?.let { return it }

    if (numericFallback) {
        val match = NUMERIC_TIMESTAMP.matchEntire(value) ?: return null
        val (year, month, day, hour, minute, second, millis) = match.destructured
        return runCatching {
            LocalDateTime.of(
                year.toInt(),
                month.toInt(),
                day.toInt(),
                hour.toInt(),
                minute.toInt(),
                second.toInt(),
                millis.ifEmpty { "0" }.padEnd(3, '0').toInt() * 1_000_000,
            ).atZone(ZoneId.systemDefault()).toInstant()
        }.getOrNull()
    }
    return null
}

/**
 * Parses the standalone log files written by the Logback encoders Kindling generates for individual loggers
 * (the "additional logs" produced by the Logback XML tool), e.g.
 *
 * ```
 * I [timestamp-test                ] [2026/08/07 16:05.14.782]: {webserver-46} test route-actor=unknown, route-group=rpc
 * ```
 *
 * These lack the `LEVEL | jvm 1 | timestamp |` prefix the service wrapper adds, so they aren't parseable by
 * [WrapperLogPanel]. They do carry a thread and MDC values, so they're presented via [SystemLogPanel] instead.
 */
object LogbackLogParser {
    /**
     * A single event line, as emitted by the encoder patterns Kindling generates:
     *
     * ```
     * %.-1p [%-30logger] [%d{...}]: {%thread} %replace(%m){"[\r\n]+", ""} %X%n
     * ```
     *
     * The `{%thread}` portion is optional; the stock `SysoutAppender` pattern omits it.
     */
    val EVENT_LINE =
        """^(?<level>[TDIWE]) \[(?<logger>[^]]++)] \[(?<timestamp>[^]]++)]: (?:\{(?<thread>[^}]*+)} )?(?<message>.*)$"""
            .toRegex()

    /**
     * The trailing `%X` (MDC map) portion of a message, which Logback writes as `key=value, key=value`.
     *
     * There's no delimiter separating the message from the MDC map, so this is necessarily a heuristic: we take
     * the longest run of comma-separated `key=value` pairs that ends the line and begins at a word boundary.
     * Keys are restricted to identifier-ish characters to avoid latching onto things like `Ignition[state=STOPPED]`.
     * A message that genuinely ends in `something=value` will have that pair hoisted into the MDC; nothing is
     * lost, since MDC values are shown in the details pane.
     */
    private val MDC_SUFFIX =
        """(?:^|(?<= ))([A-Za-z_][\w.-]*=[^,]*(?:, [A-Za-z_][\w.-]*=[^,]*)*)$""".toRegex()

    /**
     * True if [path]'s first non-blank line looks like a Logback additional log event.
     */
    fun matches(path: Path): Boolean = path.useLines(DefaultEncoding.currentValue) { lines ->
        matches(lines)
    }

    fun matches(lines: Sequence<String>): Boolean =
        lines.firstOrNull(String::isNotBlank)?.let(EVENT_LINE::matches) == true

    fun parseFile(path: Path): LogFile<SystemLogEvent> = path.useLines(DefaultEncoding.currentValue) { lines ->
        LogFile(parse(lines))
    }

    fun parse(lines: Sequence<String>): List<SystemLogEvent> {
        // resolved once so that every line in a file is parsed consistently
        val configuredFormat = configuredTimestampFormat
        val events = mutableListOf<SystemLogEvent>()
        val currentStack = mutableListOf<String>()
        var partialEvent: SystemLogEvent? = null

        fun flush() {
            partialEvent?.let { events += it.copy(stacktrace = currentStack.toList()) }
            currentStack.clear()
            partialEvent = null
        }

        for (line in lines) {
            if (line.isBlank()) {
                continue
            }

            val match = EVENT_LINE.matchEntire(line)
            if (match == null) {
                // the encoder patterns we generate don't include %nopex, so Logback appends stacktraces verbatim
                if (partialEvent == null && events.isEmpty()) {
                    throw IllegalArgumentException(
                        "Error parsing log file; unexpected content format on first line:\n$line",
                    )
                }
                currentStack += line
                continue
            }

            val timestamp = match.groups["timestamp"]!!.value.trim()
            val time = parseLogTimestamp(timestamp, configuredFormat, numericFallback = true)
            if (time == null) {
                if (events.isEmpty()) {
                    throw IllegalArgumentException(
                        "Error parsing log file; unable to read the timestamp \"$timestamp\". " +
                            "Check the Timestamp Pattern preference (currently \"${TimestampPattern.currentValue}\").",
                    )
                }
                continue
            }

            flush()

            val (message, mdc) = extractMdc(match.groups["message"]!!.value.trim())
            partialEvent = SystemLogEvent(
                timestamp = time,
                message = message,
                logger = match.groups["logger"]!!.value.trim(),
                thread = match.groups["thread"]?.value?.trim().orEmpty(),
                level = Level.valueOf(match.groups["level"]!!.value.single()),
                mdc = mdc,
                stacktrace = emptyList(),
            )
        }
        flush()
        return events
    }

    /**
     * Split the trailing MDC map, if any, off of [message]. See [MDC_SUFFIX].
     */
    private fun extractMdc(message: String): Pair<String, List<MDC>> {
        val match = MDC_SUFFIX.find(message) ?: return message to emptyList()
        val mdc = match.groupValues[1].split(", ").map { pair ->
            val (key, value) = pair.split('=', limit = 2)
            MDC(key, value)
        }
        return message.substring(0, match.range.first).trim() to mdc
    }
}