name: Publish new Dokka docs upon new version tag
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish as'
        required: true
        type: string
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'gradle'

      - name: Create Dokka docs
        run: >
          ./gradlew
          -Pversion=${{ inputs.version || github.ref_name }}
          dokkaHtml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
          destination_dir: docs
