name: Publish new version upon tag commit
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build & JPackage
        run: ./gradlew build jpackage
        env:
          TAG_VERSION: ${{github.ref_name}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: build/jpackage/
  create-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
#      - name: Create Release
#        uses: marvinpinto/action-automatic-releases@latest
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          prerelease: false
#          files: |
#            artifacts/*
#      - name: Setup Node
#        uses: actions/setup-node@v2
#        with:
#          node-version: '17'
#          registry-url: 'https://registry.npmjs.org'
#          cache: 'npm'
#      - name: Install JDeploy
#        run: npm install
#      - name: Set package version
#        run: npm --no-git-tag-version version ${{github.ref_name}}
#      - name: JDeploy Publish
#        run: npx jdeploy publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
